chore(#70): resolve merge conflicts

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -1,33 +1,46 @@
-name: test coverage
+name: Codecov Report
 
 on:
+  push:
+    branches:
+      - main
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
 jobs:
-  codecov:
+  test-and-report:
     runs-on: ubuntu-latest
-    name: run codecov
+
     steps:
-      - uses: actions/checkout@master
-      - uses: shivammathur/setup-php@v2
-        with:
-          php-version: ${{ vars.PHP_VERSION }}
-      - name: Install dependencies
-        run: composer self-update && composer install --dev --no-scripts --no-progress && composer dump-autoload
-      - name: Start Application
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Start application
         run: make start
-      - name: Setup Test Database
+
+      - name: Setup test database
         run: make setup-test-db
-      - name: Execute Unit and Integration tests
-        run: make coverage-xml
-      - name: Copy coverage report to host
-        run: docker cp php-service-template-php-1:/srv/app/coverage/coverage.xml /tmp
-      - uses: codecov/codecov-action@v3
+
+      - name: Run unit tests and collect coverage
+        run: make ci-tests
+
+      - name: Copy coverage.xml to workspace
+        run: docker cp user-service-php-1:/coverage/coverage.xml /tmp/coverage.xml
+
+      - name: Check if coverage.xml exists
+        run: |
+          if [ ! -f /tmp/coverage.xml ]; then
+            echo "coverage.xml does not exist and cannot be uploaded."
+            exit 1
+          fi
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
+          file: /tmp/coverage.xml
           flags: unittests
           name: codecov-umbrella
-          files: /tmp/coverage.xml
           fail_ci_if_error: true
           verbose: true
